In [1]:
import numpy as np

In [5]:
a = np.array([10,20,30])
b = np.array([3,5,7])


print(np.mod(a,b))
print(np.remainder(a,b))

[1 0 2]
[1 0 2]


In [10]:
a = np.array([2.0, 6.54, 143, 0.767, 65.542, 65.332])
print(np.round(a))
print(np.round(a, decimals=1))
print(np.round(a, decimals=-1))

[  2.   7. 143.   1.  66.  65.]
[  2.    6.5 143.    0.8  65.5  65.3]
[  0.  10. 140.   0.  70.  70.]


In [15]:
a = np.array([-2.7, 3.9, -0.4, 0.9, 20])
print(np.floor(a))
print(np.ceil(a))

[-3.  3. -1.  0. 20.]
[-2.  4. -0.  1. 20.]


In [22]:
a = np.array([[79,65,44,55], [65,66,78,66],[77,66,44,33]])
print(a)
print(np.amin(a))
print(np.amin(a, axis=1))
print(np.amin(a, axis=0))

[[79 65 44 55]
 [65 66 78 66]
 [77 66 44 33]]
33
[44 65 33]
[65 65 44 33]


In [23]:
print(np.amax(a))
print(np.amax(a, axis=1))
print(np.amax(a, axis=0))

79
[79 78 77]
[79 66 78 66]


In [26]:
a

array([[79, 65, 44, 55],
       [65, 66, 78, 66],
       [77, 66, 44, 33]])

In [29]:
print(np.median(a))
print(np.median(a,axis=1))
print(np.median(a,axis=0))

65.5
[60. 66. 55.]
[77. 66. 44. 55.]


In [31]:
print(np.mean(a))
print(np.mean(a, axis=1))
print(np.mean(a, axis=0))

61.5
[60.75 68.75 55.  ]
[73.66666667 65.66666667 55.33333333 51.33333333]


In [36]:
a = np.array([1,2,3,4])
wts = np.array([4,3,2,1])
print(np.average(a))
print(np.mean(a))
print(np.average(a, weights=wts))

2.5
2.5
2.0


In [38]:
np.std(a)

1.118033988749895

In [39]:
np.var(a)

1.25

In [40]:
a = np.array([[79,65,44,55], [65,66,78,66],[77,66,44,33]])

In [41]:
a

array([[79, 65, 44, 55],
       [65, 66, 78, 66],
       [77, 66, 44, 33]])

In [44]:
print(np.sort(a))
print()
print(np.sort(a,axis=1))
print()
print(np.sort(a, axis=0))

[[44 55 65 79]
 [65 66 66 78]
 [33 44 66 77]]

[[44 55 65 79]
 [65 66 66 78]
 [33 44 66 77]]

[[65 65 44 33]
 [77 66 44 55]
 [79 66 78 66]]


In [47]:
x=np.arange(9).reshape(3,3)

In [52]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [59]:
x[np.where(x<3)]

array([0, 1, 2])

In [54]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [55]:
condition = np.mod(x,2)==0

In [56]:
np.extract(condition, x)

array([0, 2, 4, 6, 8])