In [1]:
import numpy as np

In [3]:
#!pip install numpy
np.version.version

'1.16.5'

In [6]:
sales = [4543,2233,4335,3344,4543,6544,3565,3344,6543,6644,8765,3323,5654,3344,5654,7766]
profit = [454,233,443,566,777,677,555,766,455,554,665,455,345,766,444,567]

In [7]:
len(sales)
len(profit)

16

In [8]:
profit/sales

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [9]:
profitratio = []
for i in range(0,len(sales)):
    profitratio.append(profit[i]/sales[i])
profitratio

[0.099933964340744,
 0.10434393193013883,
 0.10219146482122261,
 0.16925837320574164,
 0.17103235747303544,
 0.10345354523227383,
 0.15568022440392706,
 0.229066985645933,
 0.06953996637627999,
 0.08338350391330523,
 0.07586993725042784,
 0.13692446584411677,
 0.061018747789175806,
 0.229066985645933,
 0.07852847541563494,
 0.07301055884625289]

In [11]:
sales_array = np.array(sales)

In [12]:
type(sales_array)

numpy.ndarray

In [14]:
profit_array = np.array(profit)

In [15]:
profit_array

array([454, 233, 443, 566, 777, 677, 555, 766, 455, 554, 665, 455, 345,
       766, 444, 567])

In [16]:
sales_array

array([4543, 2233, 4335, 3344, 4543, 6544, 3565, 3344, 6543, 6644, 8765,
       3323, 5654, 3344, 5654, 7766])

In [17]:
profit_array/sales_array

array([0.09993396, 0.10434393, 0.10219146, 0.16925837, 0.17103236,
       0.10345355, 0.15568022, 0.22906699, 0.06953997, 0.0833835 ,
       0.07586994, 0.13692447, 0.06101875, 0.22906699, 0.07852848,
       0.07301056])

In [19]:
import time 
start = time.time()
profitratio = []
for i in range(0,len(sales)):
    profitratio.append(profit[i]/sales[i])
profitratio
print((time.time() - start)*1000)

0.995635986328125


In [20]:
import time 
start = time.time()
profit_array/sales_array
print((time.time() - start)*1000)

0.995635986328125


In [21]:
size = 1000000
l1 = range(size)
l2 = range(size)
a1 = np.arange(size)
a2 = np.arange(size)

start = time.time()
result = [(x,y) for x,y in zip(l1,l2)]
print('Time taken by list operation')
print((time.time()-start)*1000)

start = time.time()
result = a1 + a2
print('Time taken by Array')
print((time.time()-start)*1000)

Time taken by list operation
277.42743492126465
Time taken by Array
56.849002838134766


In [22]:
cust  = ['A1', 'A2','A3','A4']
order = [1,2,3,4]
for (c,o) in zip(cust, order):
    print('Hello', c, 'Your order id is:', o)

Hello A1 Your order id is: 1
Hello A2 Your order id is: 2
Hello A3 Your order id is: 3
Hello A4 Your order id is: 4


In [49]:
list1 = [ True]

In [29]:
type(list1[3])

bool

In [50]:
array1 = np.array(list1)

In [51]:
array1

array([ True])

In [53]:
type(array1[0])

numpy.bool_

In [54]:
list1 = [32,3,44,34,54]

In [57]:
list1*2

[32, 3, 44, 34, 54, 32, 3, 44, 34, 54]

In [56]:
array1 = np.array(list1)

In [58]:
array1*2

array([ 64,   6,  88,  68, 108])

In [60]:
list2 = list1.copy()

In [63]:
list3 = list1[0:3]

In [74]:
list1[0]=1000

In [75]:
list1

[1000, 3, 44, 34, 54]

In [71]:
list2[0]=200

In [76]:
list2

[200, 3, 44, 34, 54]

In [67]:
list3[0]=100

In [77]:
list3

[100, 3, 44]

In [78]:
a1 = np.array(list1)

In [79]:
a1

array([1000,    3,   44,   34,   54])

In [80]:
a2 = a1.copy()

In [81]:
a2

array([1000,    3,   44,   34,   54])

In [83]:
a3 = a1[0:3]

In [90]:
a1[0]=100000

In [92]:
a2[0]=0

In [87]:
a3[0]=0

In [93]:
a3

array([100000,      3,     44])

In [94]:
a1

array([100000,      3,     44,     34,     54])

In [96]:
a1.dtype

dtype('int32')

In [97]:
a1.ndim

1

In [98]:
a1.shape

(5,)

In [99]:
sales_us = [4354,3345,3432,2232]
sales_eu = [5433,3433,5554,3333]
sales_jp = [2222,3242,2223,3322]

In [101]:
profit_us = [435,444,545,566]
profit_eu = [544,234,534,566]
profit_jp = [655,554,334,454]

In [103]:
sales_matrix = np.array([sales_us,sales_eu,sales_jp])

In [105]:
sales_matrix.dtype

dtype('int32')

In [106]:
sales_matrix.ndim

2

In [107]:
sales_matrix.shape

(3, 4)

In [108]:
type(sales_matrix)

numpy.ndarray

In [109]:
profit_matrix = np.array([profit_us, profit_eu, profit_jp])

In [110]:
profit_matrix

array([[435, 444, 545, 566],
       [544, 234, 534, 566],
       [655, 554, 334, 454]])

In [111]:
profit_matrix/sales_matrix

array([[0.09990813, 0.13273543, 0.15879953, 0.25358423],
       [0.10012884, 0.06816196, 0.09614692, 0.16981698],
       [0.29477948, 0.17088217, 0.15024741, 0.13666466]])

In [117]:
profit_us = [435,444,545,566]
profit_eu = [544,234,534,566]
profit_jp = [655,554,334,543]

In [118]:
profit_matrix = np.array([profit_us, profit_eu, profit_jp])

In [119]:
type(profit_matrix)
profit_matrix.ndim

2

In [121]:
profit_matrix[1,2]

534

In [124]:
profit_matrix

array([[435, 444, 545, 566],
       [544, 234, 534, 566],
       [655, 554, 334, 543]])

In [125]:
profit_matrix[:, 2:4]

array([[545, 566],
       [534, 566],
       [334, 543]])

In [133]:
profit_matrix

array([[435, 444, 545, 566],
       [544, 234, 534, 566],
       [655, 554, 334, 543]])

In [136]:
profit_matrix[0,2]

545

In [137]:
profit_matrix[0][2]

545

In [132]:
profit_matrix[rdict['US']][qdict['Q3']]

545

In [129]:
rdict = {'US':0, 'EU':1, 'JP':2}
qdict = {'Q1':0, 'Q2':1, 'Q3':2, 'Q4':3}

In [130]:
rdict['US']

0

In [131]:
qdict['Q3']

2

In [140]:
a = np.arange(1,21)`

In [148]:
np.reshape(a, (10,2), 'C' )

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])