In [1]:
import os
os.chdir(r'D:\Courses\Python Basics to Advanced')

In [47]:
import pandas as pd
df = pd.read_excel('DataPreprocessing.xlsx')

In [4]:
df

Student_Id  Marks_10  Marks_12  Marks_Grad  State  Salary
0           1      45.0       NaN        56.0    1.0      10
1           2       NaN      65.0        67.0    1.0      12
2           3      54.0      68.0        57.0    0.0      14
3           4      89.0      88.0         NaN    NaN      18
4           5       NaN      87.0        84.0    1.0      21

In [24]:
x = df.iloc[:,0:6].values

In [21]:
x

array([[ 1., 45., nan, 56.,  1., 10.],
       [ 2., nan, 65., 67.,  1., 12.],
       [ 3., 54., 68., 57.,  0., 14.],
       [ 4., 89., 88., nan, nan, 18.],
       [ 5., nan, 87., 84.,  1., 21.]])

In [11]:
import numpy as np
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imp.fit(x[:,1:5])
x[:,1:5] = imputer.transform(x[:,1:5])

In [19]:
pd.DataFrame(x)
#(45+54+89)/3
#(65+68+88+87)/4
#(56+67+57+84)/4

0          1     2     3     4     5
0  1.0  45.000000  77.0  56.0  1.00  10.0
1  2.0  62.666667  65.0  67.0  1.00  12.0
2  3.0  54.000000  68.0  57.0  0.00  14.0
3  4.0  89.000000  88.0  66.0  0.75  18.0
4  5.0  62.666667  87.0  84.0  1.00  21.0

In [22]:
import numpy as np
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy='median')
imputer = imp.fit(x[:,1:5])
x[:,1:5] = imputer.transform(x[:,1:5])

In [23]:
x

array([[ 1. , 45. , 77.5, 56. ,  1. , 10. ],
       [ 2. , 54. , 65. , 67. ,  1. , 12. ],
       [ 3. , 54. , 68. , 57. ,  0. , 14. ],
       [ 4. , 89. , 88. , 62. ,  1. , 18. ],
       [ 5. , 54. , 87. , 84. ,  1. , 21. ]])

In [25]:
import numpy as np
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy='median')
imputer = imp.fit(x[:,1:4])
x[:,1:4] = imputer.transform(x[:,1:4])

In [26]:
x

array([[ 1. , 45. , 77.5, 56. ,  1. , 10. ],
       [ 2. , 54. , 65. , 67. ,  1. , 12. ],
       [ 3. , 54. , 68. , 57. ,  0. , 14. ],
       [ 4. , 89. , 88. , 62. ,  nan, 18. ],
       [ 5. , 54. , 87. , 84. ,  1. , 21. ]])

In [27]:
import numpy as np
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imputer = imp.fit(x[:,4:5])
x[:,4:5] = imputer.transform(x[:,4:5])

In [28]:
x

array([[ 1. , 45. , 77.5, 56. ,  1. , 10. ],
       [ 2. , 54. , 65. , 67. ,  1. , 12. ],
       [ 3. , 54. , 68. , 57. ,  0. , 14. ],
       [ 4. , 89. , 88. , 62. ,  1. , 18. ],
       [ 5. , 54. , 87. , 84. ,  1. , 21. ]])

In [30]:
df1 = df

In [32]:
df1['Marks_10'] = df1['Marks_10'].fillna(df1['Marks_10'].mean())

In [33]:
df1

Student_Id   Marks_10  Marks_12  Marks_Grad  State  Salary
0           1  45.000000       NaN        56.0    1.0      10
1           2  62.666667      65.0        67.0    1.0      12
2           3  54.000000      68.0        57.0    0.0      14
3           4  89.000000      88.0         NaN    NaN      18
4           5  62.666667      87.0        84.0    1.0      21

In [34]:
df1['Marks_12'] = df1['Marks_12'].fillna(df1['Marks_12'].median())

In [36]:
df1['Marks_Grad']= df1['Marks_Grad'].fillna(df1['Marks_Grad'].median())

In [37]:
df1

Student_Id   Marks_10  Marks_12  Marks_Grad  State  Salary
0           1  45.000000      77.5        56.0    1.0      10
1           2  62.666667      65.0        67.0    1.0      12
2           3  54.000000      68.0        57.0    0.0      14
3           4  89.000000      88.0        62.0    NaN      18
4           5  62.666667      87.0        84.0    1.0      21

In [38]:
df1['State']= df1['State'].fillna(df1['State'].median())

In [39]:
df1

Student_Id   Marks_10  Marks_12  Marks_Grad  State  Salary
0           1  45.000000      77.5        56.0    1.0      10
1           2  62.666667      65.0        67.0    1.0      12
2           3  54.000000      68.0        57.0    0.0      14
3           4  89.000000      88.0        62.0    1.0      18
4           5  62.666667      87.0        84.0    1.0      21

# K-NN imputation

In [44]:
df

Student_Id  Marks_10  Marks_12  Marks_Grad  State  Salary
0           1      45.0       NaN        56.0    1.0      10
1           2       NaN      65.0        67.0    1.0      12
2           3      54.0      68.0        57.0    0.0      14
3           4      89.0      88.0         NaN    NaN      18
4           5       NaN      87.0        84.0    1.0      21

In [48]:
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=1)
df = imputer.fit_transform(df)

In [49]:
df

array([[ 1., 45., 68., 56.,  1., 10.],
       [ 2., 54., 65., 67.,  1., 12.],
       [ 3., 54., 68., 57.,  0., 14.],
       [ 4., 89., 88., 84.,  1., 18.],
       [ 5., 89., 87., 84.,  1., 21.]])